apiVersion: v1
kind: Service
metadata:
  name: registerapp-service
  labels:
    app: register-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  externalIPs:
    192.168.68.92
  selector:
    app: register-app